### ISSUE TITLE
Structure not clear

### ISSUE THREAD

**Issue by Bers00** [FiliTol/stacker-news#6]
Why you are saving link, discussion, etc.. in different dataset? Is it better to have just a factor column representing the type of post?

**Comment by FiliTol** [comment]
Yeah you are absolutely right, I was just testing with different csv to see how the script handled it. I'm gonna unify everything in a single csv.
Just an insight: as far as I observed with regards to posts, the majority of them are links, with a proportion of 9 out of 10.

**Comment by FiliTol** [comment]
I'm going to close the issue once I will get this fixed

**Comment by FiliTol** [comment]
I'm writing this down for tracking purposes.
@Bers00 I thought about the sctructure of the scraping chunck as you proposed and I agree that it would be much faster and efficient to manage it using that workflow.

We should sit down a few minutes and agree on which fields we definitely need to extract from the different item types. There are a lot of similarities between `poll`, `bounty` and `discussion` items and if we agree to treat them in the same way (with regards to the extracted fields) we could unify the scraping functions and strucure. 

This will lead to a final chunck in which the if-elif test is done only 3 times:

- link item
- discussion, poll or bounty item
- comment item

**Comment by FiliTol** [comment]
This issue thread is related to #7 

Another remark about the scraping chunck: the structure can probably be optimized by ordering the if-elif conditions based on the amount of items for each category tested in the if clause.

Assuming that comments are the most present item among all the items, the order in which  if-elif elements could be tested is:

1. Comments 
2. Links
3. Discussion
4. Poll
5. Bounty
6. Job offer

Since job offers are the least present item, give no useful information (a part from the whole text of the offer) and are an extremely small number (which can be visualized in the homepage of [stacker.news jobs](https://stacker.news/~jobs) ) we could even decide to trash them.
